---
# handlers file for ntp-client

- name: Restart ntpd
  service:
    name: '{{ ntpd_service[ansible_os_family] }}'
    state: restarted

- name: Restart systemd-timesyncd
  service:
    name: systemd-timesyncd
    state: restarted
